[workspace]
resolver = "2"
members = [
    "crates/rustline-abi",
    "crates/rustline-core",
    "crates/rustline",
    "crates/rustline-wasm",
    "crates/rustline-plugin-sdk",
]
exclude = [
    "plugins/weather",
    "plugins/counter",
    "plugins/filewatch",
    "plugins/httpget",
    "plugins/cmdrun",
]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "MIT"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
